
-- Create unified StatusHistory table that handles both orders and deliveries
CREATE TABLE IF NOT EXISTS "StatusHistory" (
  "status_history_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "entity_type" varchar NOT NULL, -- 'order' or 'delivery'
  "entity_id" int NOT NULL,
  "status" varchar NOT NULL,
  "updated_at" timestamp DEFAULT (now()),
  "updated_by" int,
  "notes" text
);

-- Add foreign key constraints
ALTER TABLE "StatusHistory" ADD CONSTRAINT fk_status_history_updated_by 
FOREIGN KEY ("updated_by") REFERENCES "User" ("user_id");


-- Add indexes for better performance
CREATE INDEX IF NOT EXISTS idx_status_history_entity 
ON "StatusHistory" ("entity_type", "entity_id", "updated_at");


