CREATE TABLE "InventoryTransferLog" (
  "transfer_id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "order_id" int NOT NULL,
  "order_item_id" int NOT NULL,
  "product_id" int NOT NULL,
  "source_warehouse_id" int NOT NULL,
  "target_warehouse_id" int NOT NULL,
  "quantity_transferred" int NOT NULL,
  "source_stock_before" int NOT NULL,
  "source_stock_after" int NOT NULL,
  "target_stock_before" int NOT NULL,
  "target_stock_after" int NOT NULL,
  "transfer_reason" varchar DEFAULT 'ORDER_FULFILLMENT',
  "transfer_date" timestamp DEFAULT (now()),
  "distance_km" decimal(10,2),
  "created_at" timestamp DEFAULT (now())
);

-- Add foreign key constraints
ALTER TABLE "InventoryTransferLog" ADD FOREIGN KEY ("order_id") REFERENCES "Order" ("order_id");
ALTER TABLE "InventoryTransferLog" ADD FOREIGN KEY ("order_item_id") REFERENCES "OrderItem" ("order_item_id");
ALTER TABLE "InventoryTransferLog" ADD FOREIGN KEY ("product_id") REFERENCES "Product" ("product_id");
ALTER TABLE "InventoryTransferLog" ADD FOREIGN KEY ("source_warehouse_id") REFERENCES "Warehouse" ("warehouse_id");
ALTER TABLE "InventoryTransferLog" ADD FOREIGN KEY ("target_warehouse_id") REFERENCES "Warehouse" ("warehouse_id");

-- Add indexes for better query performance
CREATE INDEX ON "InventoryTransferLog" ("order_id");
CREATE INDEX ON "InventoryTransferLog" ("product_id");
CREATE INDEX ON "InventoryTransferLog" ("source_warehouse_id");
CREATE INDEX ON "InventoryTransferLog" ("target_warehouse_id");
CREATE INDEX ON "InventoryTransferLog" ("transfer_date");
